### ISSUE TITLE
[Orangelight:alma_qa] alma_qa playbook will not add alma keys on the alma_qa1 box

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1658]

**Comment by hackmastera** [comment]
@christinach what are the keys and where can I find the desired values?

**Comment by christinach** [comment]
You can find them in the last pass in the Shared ITIMS

**Comment by christinach** [comment]
@hackmastera ^

**Comment by hackmastera** [comment]
So it looks like these are:

- ALMA_ACQ_READ_WRITE
- ALMA_BIB_READ_WRITE
- ALMA_BIBS_READ_ONLY
- ALMA_CONFIG_READ_ONLY
- ALMA_USERS_READ_ONLY

**Comment by hackmastera** [comment]
The `orangelight` role depends on the `blacklight-app` role which depends on `rails-app` which runs the task that sets up the env. Everything looks set up correctly to me. I'm going to run it.

**Comment by hackmastera** [comment]
The problem is that it's pulling from `roles/pulibrary.orangelight/vars/main.yml`. This file has a really high precedence and can't be overridden by playbook or group_vars. `defaults/main.yml` is the place to put defaults for a role, unless we never expect it to change from playbook to playbook (an example from @kayiwa in slack was "upstream repo keys"). Otherwise we should keep settings in group_vars files.
