### ISSUE TITLE
GeoServer playbook can't be re-run

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/princeton_ansible#214]
- There is a problem with running deploy_user role. Deploy user already exists.
- Samba role can't be re-run. Shares already exist.
- I'm concerned that deploying the geoserver role might overwrite the geoserver app directory.

**Comment by eliotjordan** [comment]
Will need help from @kayiwa on this, since he set up the machine originally.

**Comment by acozine** [comment]
@eliotjordan is this still a concern? Most if not all of our roles are idempotent now - certainly the `deploy_user` role can be run multiple times without any destructive behavior. If you're concerned about the geoserver app directory, I'd be happy to pair up and run the playbook with appropriate precautions, and fix anything in the playbook that turns out to be destructive on a second run.

**Comment by acozine** [comment]
Closing as likely obsolete. If this is still a problem, feel free to open a new issue.

**Comment by eliotjordan** [comment]
Unfortunately this is still an issue. A second run is destructive. We just haven't had the time / developer energy to fix this yet.

**Comment by acozine** [comment]
We have now retired the geoserver machine. Closing this ticket as #wontfix.
