### ISSUE TITLE
nginxplus: only the configs in our config directory should exist on the server

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2750]
e.g. if an old config is removed from ansible it should also be removed from the remote server.

Current behavior is that the old config is still there after the playbook has been run.

**Comment by acozine** [comment]
The current role has a [tasks file](url) with a single task that "cleans up" the config. It removes the entire config directory. The role [includes that file](https://github.com/pulibrary/princeton_ansible/blob/d4d542853cd6ca102be7da6e3f4ecf66f666b0f6/roles/nginxplus/tasks/main.yml#L22) only when the variable `nginx_cleanup_config` is set to `true` - that var is set to `false` in the role defaults.

Do we want that task to run every time we upload new configs? So that each time the playbook runs (unless it runs with `-t SSL`) , it would delete the config directory and upload all configs from scratch? If so, we can put it in the `upload_config.yml` tasks file, before the upload task, and tag it with `tags: update_conf`. 

If we only want that task to run occasionally, we can update the README and playbooks to document the existing behavior: "To remove all existing config files before uploading, pass `-e nginx_cleanup_config=true` when you run the playbook."

**Comment by acozine** [comment]
Per @tpendragon we can use the [synchronize module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html) with `delete`.

**Comment by acozine** [comment]
Test for this as part of #3439

**Comment by acozine** [comment]
Related to #4654 - I think that PR should fix/close this ticket.
