### ISSUE TITLE
completely uninstall all ruby

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3117]
The `ruby_s` role should completely uninstall all versions of ruby that are
still left on a vm. This is especially needed when one is trying to use `ruby_s`
for the ruby version 2

**Comment by acozine** [comment]
This ticket was prompted by a problem updating lib-jobs.princeton.edu in mid-June, after changing the playbook to run the `ruby_s` role instead of the `ruby` role. The playbook ran fine, but the first deploy after the playbook run failed. On investigation, it turned out there were multiple versions of ruby installed on the box. We suspect that the ruby version passenger was using was not the newly installed version. Gist of the run: https://gist.github.com/pulbot/ad1588075adb2d5bca178211089cdbfb

**Comment by acozine** [comment]
Related to #3114.

**Comment by acozine** [comment]
I think this will be solved/fixed by 808a249c8c6dd213f82dd6b6b4b1b2981374e982, which is part of #3373.

**Comment by acozine** [comment]
If we want to use the ruby_s role to upgrade/downgrade ruby versions, we also need to run `make uninstall` from the directory for the old ruby version before installing the new one.

**Comment by acozine** [comment]
Closed (as "good enough") by #3414.
