### ISSUE TITLE
Allow upgrading bundler version alone

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3423]
Right now the `ruby_s` role only changes the version of bundler if/when you are also changing the version of ruby.

We would like to have the ability to change the version of bundler while keeping the existing version of ruby in place.

This likely involves:
- [ ] pulling the bundler-related tasks into a separate tasks file
- [ ] adding a check in tasks/main.yml to see if the installed bundler version matches the desired bundler version
- [ ] figuring out how to force-install a specific version of bundler

**Comment by christinach** [comment]
The ruby interpreter will install a specific bundler version. In order to change this you need to change the ruby version and use a different bundler version. 
Locally when I want to use a different bundler version to bundle the gems:
1. I install the bundler version I want and then I run `bundle _theversionnumber_ install`
2. If the previous installed version is marked as default step 1 will not work. Then I need to look in the `specifications/default` directory and remove it from there. 
3. `gem env` provides the installation path which is `INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/3.1.0` . You can check what is installed as default in `/usr/local/lib/ruby/gems/{ruby_version}/specifications/default/`. In the bibdata-alma-staging case it indicates that bundler default is `bundler-2.3.25.gemspec`. In order to change the default : 
4.  i) `rm  /usr/local/lib/ruby/gems/{ruby_version}/specifications/default/bundler-2.3.25.gemspec` , ii) reinstall the desired ruby version as default ,  iii) uninstall the previous installed version.  
This needs to be well tested as there might be more than one bundler defaults in the default directory.

**Comment by kayiwa** [comment]
closed by this #3700
