### ISSUE TITLE
Failed to update apt cache: unknown reason

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3560]
One of our roles is introducing an old expired repository key that makes it impossible for the 

```zsh
apt -y update && apt -y upgrade
```

to run which is needed to uninstall the Brightbox Repository. It is likely to be in the [common](roles/common) and/or [ruby](roles/ruby)

**Comment by sandbergja** [comment]
This was the error message I saw when I ran `apt-get update` on the repec-prod1:

```
Err:12 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
Fetched 4,949 B in 1s (4,723 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
W: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/bionic-pgdg/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by kayiwa** [comment]
For now run the https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/update_expired_certs.yml

**Comment by acozine** [comment]
@kayiwa does #3672 fix this issue?

**Comment by VickieKarasic** [comment]
As of today, pulfalight-prod1 is still failing the apt cache update on Patch Tuesdays.

**Comment by acozine** [comment]
I believe since #4114 was merged, updating the abid playbook to use the `ruby_s` role, we have eliminated the Brightbox PPA (which was installed by the old `ruby` role) from all our infrastructure. We should not need to remove it again in future.

More recently we've seen issues with stale keys for postgresql on the boxes listed in @VickieKarasic's comment above. The production boxes are now all fixed. We will open a separate ticket for the staging boxes still failing the Patch Tuesday playbook.

Also related to https://github.com/pulibrary/pul-it-handbook/pull/203.
