### ISSUE TITLE
redirect hishi URL

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3706]
The following URI https://library.princeton.edu/eastasian/hishi/ needs to point to https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=%22hishi+collection%22

**Comment by kevinreiss** [comment]
Hi, instead of a proxy pass rule we I need to make the change in https://github.com/pulibrary/princeton_ansible/issues/3706 to be a redirect rather a proxy pass rule. So the old public URL of https://library.princeton.edu/eastasian/hishi/ is just redirected to the new catalog URL we've selected to be the landing page for this collection, https://eal-apps-prod.princeton.edu/hishi/ has never been a URL in public circulation so I'm not sure we even need to muck with it.
