### ISSUE TITLE
ansible-tower galaxy error

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4730]
when trying to run the OS Updates patch playbook the following error occurs trying to fetch the galaxy collection 

```
TASK [Fetch galaxy collections from collections/requirements.(yml/yaml)] *******
failed: [localhost] (item=/var/lib/awx/projects/_11__prancible/collections/requirements.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["ansible-galaxy", "collection", "install", "-r", "/var/lib/awx/projects/_11__prancible/collections/requirements.yml", "--collections-path", "/var/lib/awx/projects/.__awx_cache/_11__prancible/stage/requirements_collections"], "delta": "0:01:58.012676", "end": "2024-03-05 08:02:05.093060", "item": "/var/lib/awx/projects/_11__prancible/collections/requirements.yml", "msg": "non-zero return code", "rc": 250, "start": "2024-03-05 08:00:07.080384", "stderr": "[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an\nunexpected error when getting available versions of collection google.cloud:\n'results'\nERROR! Unexpected Exception, this is probably a bug: 'results'", "stderr_lines": ["[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an", "unexpected error when getting available versions of collection google.cloud:", "'re…
```

**Comment by acozine** [comment]
It looks like all jobs on the default EE are failing with the same error - the daily updates for the project and inventory failed too.

**Comment by acozine** [comment]
A little research on this error suggests that there is some limit to the number of cached versions of a collection that the ansible-galaxy command can handle. However, our new custom EE is now ready, so instead of fixing this error, I've switched our Templates over to use the new EE, which has all our collections pre-installed on it. See #4702, which removes the `requirements.yml` file and adds the ability to create custom EEs for princeton_ansible.
